### ISSUE TITLE
General: Exception when trying to install EF Core tools from plugin

### ISSUE THREAD

**Issue by kkanjuh** [seclerp/rider-efcore#103]
When I open .Net6 project in Rider I got exception. Below is call stack.

- OS: macOS Monterey 12.5
- .NET SDK info (installed ones and version used within Rider): Net6
- Plugin version: 222.0.0
- Rider version: 2022.2.3345.139

Exception
`java.lang.NullPointerException: Cannot invoke "java.io.File.toString()" because the return value of "com.intellij.execution.configurations.GeneralCommandLine.getWorkDirectory()" is null
                at me.seclerp.rider.plugins.efcore.cli.execution.CliCommand.<init>(CliCommand.kt:12)
                at me.seclerp.rider.plugins.efcore.cli.api.ManagementCommandFactory.installEfCoreTools(ManagementCommandFactory.kt:17)
                at me.seclerp.rider.plugins.efcore.features.eftools.InstallDotnetEfAction$actionPerformed$1.invoke(InstallDotnetEfAction.kt:18)
                at me.seclerp.rider.plugins.efcore.features.eftools.InstallDotnetEfAction$actionPerformed$1.invoke(InstallDotnetEfAction.kt:11)
                at me.seclerp.rider.plugins.efcore.cli.execution.ExtensionsKt$executeCommandUnderProgress$$inlined$runBackgroundableTask$1.run(progress.kt:36)
                at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
                at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
                at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
                at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
                at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
                at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
                at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
                at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
                at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
                at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
                at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
                at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
                at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
                at java.base/java.lang.Thread.run(Thread.java:833) 
`

**Comment by seclerp** [comment]
Do you open **a solution** or just **a project** in Rider?

**Comment by kkanjuh** [comment]
I open solution

**Comment by luylucas10** [comment]
I've the same, but after install [dotnet tool install --global dotnet-ef], it was stopped. I'm using --version 5.0.17, but I think that the last version works too.

**Comment by seclerp** [comment]
From the stack trace, I see that the issue occurs after clicking the "Install" button when EF Core is not installed.

@luylucas10 this is your case too?

**Comment by markusschaber** [comment]
The same here. I opened a solution from another team which uses EF Core, and Rider suggested installing the plugin, which I accepted. On the relatively fresh installation, the EF Core Tools were not yet installed.

**Comment by seclerp** [comment]
I was able to reproduce it yesterday and created a fix. It will be available from the next version of plugin. Thanks!

**Comment by luylucas10** [comment]
> From the stack trace, I see that the issue occurs after clicking the "Install" button when EF Core is not installed.
> 
> @luylucas10 this is your case too?

Yes, after install it, works like a charm

**Comment by kkanjuh** [comment]
New version work fine. THX
