### ISSUE TITLE
Illegal scheduler exception in Rider 2022.2

### ISSUE THREAD

**Issue by KrylovBoris** [seclerp/rider-efcore#104]
#### Exception

```
Illegal scheduler for current action, must be: JetBrains.Platform.RdFramework.Impl.ShellRdDispatcher, current thread: JetPool(S) #1:14, debug info: property `MainProtocol.SolutionModel.solutions.[1].riderEfCoreModel.availableStartupProjects` (16252718103995813156)

--- EXCEPTION #1/1 [LoggerException]
Message = "Illegal scheduler for current action, must be: JetBrains.Platform.RdFramework.Impl.ShellRdDispatcher, current thread: JetPool(S) #1:14, debug info: property `MainProtocol.SolutionModel.solutions.[1].riderEfCoreModel.availableStartupProjects` (16252718103995813156)"
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600
StackTraceString = "
  at JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex)
     at JetBrains.Diagnostics.Log.SwitchingLog.JetBrains.Diagnostics.ILog.Log(LoggingLevel level, String message, Exception exception)
     at JetBrains.Diagnostics.LogEx.LogFormat(ILog this, LoggingLevel level, String message, Object[] args)
     at JetBrains.Diagnostics.LogEx.Error(ILog this, String message, Object[] args)
     at JetBrains.Collections.Viewable.SchedulerEx.AssertThread(IScheduler scheduler, Object debugInfo)
     at JetBrains.Rd.Base.RdReactiveBase.AssertThreading()
     at JetBrains.Rd.Base.RdReactiveBase.UsingLocalChange()
     at JetBrains.Rd.Impl.RdProperty`1.set_Value(T value)
     at Rider.Plugins.EfCore.EfCoreSolutionComponent.InvalidateStartupProjects() in /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/EfCoreSolutionComponent.cs:line 148
     at Rider.Plugins.EfCore.Compatibility.NugetDependenciesListener.<SetupInitialProcessingListener>b__8_0(PropertyChangedEventArgs`1 args) in /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/Compatibility/NugetDependenciesListener.cs:line 38
     at JetBrains.DataFlow.Signal`1.Fire(TValue value, Object cookie)
     at JetBrains.DataFlow.Property`1.SetValue(TValue value, Object cookie)
     at JetBrains.DataFlow.Property`1.SetValue(TValue value)
     at JetBrains.ProjectModel.NuGet.Packaging.NuGetPackageReferenceTracker.<>c__DisplayClass31_0.<.ctor>b__10()
     at JetBrains.Application.Threading.Tasks.TaskHost.AccessViolationCatcher(Action action)
     at JetBrains.Application.Threading.Tasks.TaskHost.<>c__DisplayClass36_0.<Create>b__0(Object state)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
     at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask()
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc()
     at JetBrains.Util.Reflection.CallStackAnnotation.CatchAnnotatedInvocation[TClassOfNewFrame](String methodNameOfNewFrame, Action actionToAnnotate)
     at JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.<>c__DisplayClass6_0.<.ctor>b__0()
     at System.Threading.Thread.StartCallback()
```

### Environment:

- OS: Windows
- .NET SDK info (installed ones and version used within Rider): .NET 6.0.6
- Plugin version: 222.0.0
- Rider version: 2022.2

**Comment by seclerp** [comment]
Hi,

What means `n/a` in the Plugin version field? If you are using `222.0.0` version of the plugin you should update to `222.1.0` version, it contains a fix for that issue.

**Comment by KrylovBoris** [comment]
Apologies. I wasn't able to find the version in the logs. Now I can confirm that the plugin version is in fact 222.0.0. Thank you for your reply, I'll relay it to the team
