### ISSUE TITLE
EntityFrmaework Core UI is not started in JetBrains Rider

### ISSUE THREAD

**Issue by vmakharashvili** [seclerp/rider-efcore#157]
#### Describe the bug

When I click the plugin to run, it didn't run.
The project is on .net core 2.1. I'm suspitious, maybe it's related with the sdk version.
**To Reproduce**

1. Go to 'Tools'
2. Click 'Entity Framework Core UI

#### Screenshots
![image](https://user-images.githubusercontent.com/16862175/230294718-de2b6267-6902-4c3e-86ac-94e85693d14f.png)

### Environment (please complete the following information):

- OS: Windows 11
- .NET SDK info (installed ones and version used within Rider): 2.1
- Plugin version: 231.0.2-eap04
- Rider version: 2023.1

#### Additional context

##Stacktrace
java.lang.NullPointerException
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDataContext$initBindings$1.invoke(CommonDataContext.kt:37)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDataContext$initBindings$1.invoke(CommonDataContext.kt:35)
	at me.seclerp.observables.ObservableExKt$bind$1.invoke(ObservableEx.kt:9)
	at me.seclerp.observables.ObservableExKt$bind$1.invoke(ObservableEx.kt:8)
	at me.seclerp.observables.Event.invoke(Event.kt:17)
	at me.seclerp.observables.ObservableProperty$setter$1.invoke(ObservableProperty.kt:22)
	at me.seclerp.observables.ObservableProperty$setter$1.invoke(ObservableProperty.kt:18)
	at me.seclerp.observables.ObservableProperty.setValue(ObservableProperty.kt:14)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDataContext.initData(CommonDataContext.kt:70)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDialogWrapper.initData(CommonDialogWrapper.kt:168)
	at me.seclerp.rider.plugins.efcore.features.shared.dialog.CommonDialogWrapper.initUi(CommonDialogWrapper.kt:88)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.<init>(AddMigrationDialogWrapper.kt:47)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction.createDialog(AddMigrationAction.kt:15)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction.createDialog(AddMigrationAction.kt:9)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.openDialog(BaseCommandAction.kt:67)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction.access$openDialog(BaseCommandAction.kt:27)
	at me.seclerp.rider.plugins.efcore.features.shared.BaseCommandAction$actionPerformed$1.run$lambda$0(BaseCommandAction.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:209)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:191)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:456)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:79)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:122)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:41)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:788)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:731)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:758)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:666)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$7(IdeEventQueue.kt:570)
	at com.intellij.openapi.application.impl.ApplicationImpl.withoutImplicitRead(ApplicationImpl.java:1446)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:570)
	at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:68)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:348)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:348)
	at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:343)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:994)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:994)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$4(IdeEventQueue.kt:343)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:831)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:385)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by seclerp** [comment]
Hi @vmakharashvili, unfortunately, the minimal supported version of EF Core in projects and tooling is 3.1. Supported TFMs from the [requirements section](https://github.com/seclerp/rider-efcore#requirements):
> net8.0 (preview)
> net7.0
> net6.0
> net5.0
> netcoreapp3.1
> netstandard2.1 (only for Migrations projects)
> netstandard2.0 (only for Migrations projects)
