### ISSUE TITLE
Does not seem to work with Rider installed on MacOS

### ISSUE THREAD

**Issue by haarhoff-frs** [seclerp/rider-efcore#37]
Hi, 

I'm forced to use MacOs at work, and tried to use install the plugin today, but unfortunately the plugin doesn't seem to be able to find dotnet. 
In the Event log, I can see the following: 
```
13.01.22
11:45	EF Core tools are not installed
			These tools are required to execute EF Core commands
			Fix

11:45	EF Core command failed
			Command: dotnet tool install --global dotnet-ef
			
			Output:
			java.io.IOException: Cannot run program "dotnet": error=2, No such file or directory
			
			Exit code: -1
			Try Again
```

Using dotnet and dotnet-ef over the normal terminal and Riders integrated terminal works normally, so it seems to be available in the PATH. I'm using dotnet 6.0.101.

I'm using
Rider 2021.3.2
Entity Framework Core UI: 1.1.2
MacOS 11.6.1

Any idea why that might be happening or what I can do to get it working? 
If you do not have access to a Mac I'm happy to further assist.

**Comment by seclerp** [comment]
Hi @haarhoff-frs, thanks for the bug report. It seems like it's a known issue with Java on Mac OS X, I will post a potential fix here a bit later, will be happy if you will be able to test it :)

**Comment by seclerp** [comment]
Hey @haarhoff-frs, could you try this one?

[riderefcore-1.1.2.1.zip](https://github.com/seclerp/rider-efcore/files/7863805/riderefcore-1.1.2.1.zip)

**Comment by haarhoff-frs** [comment]
Hey @seclerp 
Sorry, that did not resolve the issue, same as before. Are there any logs or anything else I could provide you with that would help?

**Comment by seclerp** [comment]
I will rewrite the whole logic for command execution to use the Intellij way, not the JDK way. I believe it will solve the problem.

**Comment by seclerp** [comment]
@haarhoff-frs could you check this one?

[riderefcore-1.1.2.2.zip](https://github.com/seclerp/rider-efcore/files/7864674/riderefcore-1.1.2.2.zip)

Before install please remove the old plugin (with restart) for a more clear check.

P.S. Please install the whole `.zip` file, not only the internal `.jar` file.

**Comment by haarhoff-frs** [comment]
That did it, no more error messages! I was able to create and remove migrations as well as update the database without any problems.
Thanks a lot for the great plugin and resolving my issue so quickly :)

**Comment by magicnov** [comment]
Hello. It seems like this issue exist on new versions. Rider version 2022.2.3, plugin version 222.2.0

com.intellij.execution.process.ProcessNotCreatedException: Cannot run program "dotnet": error=2, No such file or directory
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:362)
	at com.intellij.execution.process.OSProcessHandler.startProcess(OSProcessHandler.java:92)
	at com.intellij.execution.process.OSProcessHandler.<init>(OSProcessHandler.java:45)
	at com.intellij.execution.process.CapturingProcessHandler.<init>(CapturingProcessHandler.java:20)
	at com.intellij.execution.util.ExecUtil.execAndGetOutput(ExecUtil.kt:88)
	at me.seclerp.rider.plugins.efcore.cli.execution.CliCommand.execute(CliCommand.kt:22)
	at me.seclerp.rider.plugins.efcore.features.eftools.InstallDotnetEfAction$actionPerformed$1.invoke(InstallDotnetEfAction.kt:18)
	at me.seclerp.rider.plugins.efcore.features.eftools.InstallDotnetEfAction$actionPerformed$1.invoke(InstallDotnetEfAction.kt:11)
	at me.seclerp.rider.plugins.efcore.cli.execution.ExtensionsKt$executeCommandUnderProgress$$inlined$runBackgroundableTask$1.run(progress.kt:36)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
	at com.intellij.codeWithMe.ClientId$Companion$decorateFunction$2.apply(ClientId.kt:307)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.IOException: Cannot run program "dotnet" (in directory "/Users/mkurbanov/RiderProjects/Vpnafty"): error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1143)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1073)
	at com.intellij.execution.configurations.GeneralCommandLine.startProcess(GeneralCommandLine.java:438)
	at com.intellij.execution.configurations.GeneralCommandLine.createProcess(GeneralCommandLine.java:352)
	... 30 more
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:314)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:244)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1110)
	... 33 more

**Comment by seclerp** [comment]
@magicnov are you sure that your issue is not related to #92 ?

**Comment by magicnov** [comment]
> @magicnov are you sure that your issue is not related to #92 ?

Yes, i think i have same problem, but on macos. Is there any solution for now?

**Comment by seclerp** [comment]
Check the following:
1. You should have .NET SDK (al least 3.1) installed
2. You should have "dotnet" CLI command accessible (check your PATH env variable)

If all from above is correct, you should be able to execute `dotnet --version` from the command line:
```bash
> dotnet --version
7.0.100-preview.7.22377.5
```

Also, note that you need EF Core Tools to execute commands. The plugin should hint you to install it but you could also do it manually:

`dotnet tool install dotnet-ef --global`

And check it after installation:

`dotnet ef --help`
