### ISSUE TITLE
Error: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.

### ISSUE THREAD

**Issue by andreqGavMineral** [seclerp/rider-efcore#67]
Hey! I ran into a problem while trying to use the plugin:

```
com.jetbrains.rd.util.reactive.RdFault: Ссылка на объект не указывает на экземпляр объекта., reason: System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в Rider.Plugins.EfCore.Extensions.PsiExtensions.ToMigrationInfo(IClass class) в /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/Extensions/PsiExtensions.cs:строка 22
   в Rider.Plugins.EfCore.EfCoreSolutionComponent.<>c.<GetAvailableMigrations>b__5_2(IClass migrationClass) в /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/EFCoreSolutionComponent.cs:строка 108
   в System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   в System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   в System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   в Rider.Plugins.EfCore.EfCoreSolutionComponent.GetAvailableMigrations(Lifetime lifetime, String projectName) в /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/EFCoreSolutionComponent.cs:строка 104
   в JetBrains.Rd.Tasks.RdCall`2.OnWireReceived(UnsafeReader reader)
	at com.jetbrains.rd.framework.RdTaskResult$Companion.read(TaskInterfaces.kt:30)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:94)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:55)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:11)
	at com.jetbrains.rdclient.protocol.RdDispatcher.pumpProtocolQueue(RdDispatcher.kt:72)
	at com.jetbrains.rd.platform.protocol.SwitchingScheduler.pumpProtocolQueue(SwitchingScheduler.kt:19)
	at com.jetbrains.rider.services.RiderGlobalProgressHostKt.runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:103)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.c(RiderGlobalProgressHost.kt:89)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.access$runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:65)
	at com.jetbrains.rider.services.RiderGlobalProgressHost.runProgress(RiderGlobalProgressHost.kt:62)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runUnderProgress(Extensions.kt:121)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.refreshAvailableMigrations(AddMigrationDialogWrapper.kt:115)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.onMigrationsProjectChanged(AddMigrationDialogWrapper.kt:104)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.access$onMigrationsProjectChanged(AddMigrationDialogWrapper.kt:19)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper$1.invoke(AddMigrationDialogWrapper.kt:44)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper$1.invoke(AddMigrationDialogWrapper.kt:44)
	at me.seclerp.rider.plugins.efcore.Event.invoke(Event.kt:16)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.migrationsProjectSetter(EfCoreDialogWrapper.kt:219)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.initPreferredProjects(EfCoreDialogWrapper.kt:106)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.access$initPreferredProjects(EfCoreDialogWrapper.kt:23)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1$1.invoke(EfCoreDialogWrapper.kt:144)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1$1.invoke(EfCoreDialogWrapper.kt:141)
	at com.intellij.ui.dsl.builder.impl.RowImpl.panel(RowImpl.kt:170)
	at com.intellij.ui.dsl.builder.impl.RowImpl.panel(RowImpl.kt:45)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$panel$1.invoke(PanelImpl.kt:158)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$panel$1.invoke(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:69)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.Panel$DefaultImpls.row$default(Panel.kt:52)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.panel(PanelImpl.kt:157)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.panel(PanelImpl.kt:24)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1.invoke(EfCoreDialogWrapper.kt:141)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1.invoke(EfCoreDialogWrapper.kt:140)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:21)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.createMainUI(EfCoreDialogWrapper.kt:140)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.createCenterPanel(EfCoreDialogWrapper.kt:137)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1309)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.<init>(AddMigrationDialogWrapper.kt:47)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction$ready$dialog$1.invoke(AddMigrationAction.kt:14)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction$ready$dialog$1.invoke(AddMigrationAction.kt:13)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreAction.buildDialogInstance(EfCoreAction.kt:69)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction.ready(AddMigrationAction.kt:13)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreAction$actionPerformed$1.run$lambda-0(EfCoreAction.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:214)
	at com.intellij.openapi.application.TransactionGuardImpl.access$200(TransactionGuardImpl.java:21)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:196)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:348)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:82)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:131)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:187)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:891)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:760)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:447)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:818)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:446)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:805)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

There are several projects in my solution.
But only one project has this problem.

**Comment by kolosovpetro** [comment]
Hi. Please send us you project structure (including screenshots) or even better -- share it to github so that we will be able to reproduce the bug. 

Thanks

**Comment by andreqGavMineral** [comment]
So, I found the problem.
One of my team members accidentally removed the Migration attribute from one migration class

Thanks for the quick response :)
I am sorry to bother you
