### ISSUE TITLE
General: incorrect behaviour of EF Core tools version retrieval

### ISSUE THREAD

**Issue by LedgendODST** [seclerp/rider-efcore#71]
Hello, i just installed this amazing plugin and it seems to be not working well, it seems like it wont detect my dotnet ef (i installed it) but Rider seems like to not detect it, any fix for that?

![image](https://user-images.githubusercontent.com/55636493/163806481-d49fa517-a561-4cf2-a707-594aeae94823.png)

![image](https://user-images.githubusercontent.com/55636493/163806441-9654d25e-7671-48dd-92fb-0f5a5b1063d0.png)

**Comment by seclerp** [comment]
Hey @LedgendODST, are you able to execute any command through one of the command dialogs without errors?

**Comment by LedgendODST** [comment]
Hey @seclerp the only error i got when i try to migrate db stuff is but i get "Done. To undo this action, use 'ef migrations remove'" so it seems like to work fine!

PS C:\Users\huett\RiderProjects\Cottage\SampleBot> dotnet ef migrations add AddedVerificationCode
Build started...
Build succeeded.
Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException: Exception of type 'Microsoft.Extensions.Hosting.HostFactoryResolver+HostingListener+StopTheHostException' was thrown.
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.OnNext(KeyValuePair`2 value)
   at System.Diagnostics.DiagnosticListener.Write(String name, Object value)
   at Microsoft.Extensions.Hosting.HostBuilder.Write[T](DiagnosticSource diagnosticSource, String name, T value)
   at Microsoft.Extensions.Hosting.HostBuilder.ResolveHost(IServiceProvider serviceProvider, DiagnosticListener diagnosticListener)
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Program.<Main>$(String[] args) in C:\Users\\RiderProjects\\SampleBot\Program.cs:line 68
Done. To undo this action, use 'ef migrations remove'

i post my code below if that would help out.

[My Code](https://pastebin.com/WcHf7wJ6)

**Comment by LouisMilesRH** [comment]
I am getting the same issue (although I am running ef version 6.0.4)

![image](https://user-images.githubusercontent.com/59727334/164241039-03039628-98e1-4f50-bce2-119d881f8fc2.png)

![image](https://user-images.githubusercontent.com/59727334/164241105-bac692f2-3e4d-49da-a2c3-5a7cae500bdf.png)

**Comment by seclerp** [comment]
@LouisMilesRH are you able to execute any command using command's dialog?

**Comment by LouisMilesRH** [comment]
No I get the same error regardless of which option I choose...

**Comment by LouisMilesRH** [comment]
@seclerp @LedgendODST 

I managed to fix mine - it seems that the .dotnet\tools folder was not in the PATH variable within Powershell (in other words while dotnet ef --version worked fine from Command Prompt it would fail from PowerShell and from Terminal within Rider).

I am by no means an expert on Windows Paths (and how they get set/used) however running the following command from Powershell...

$Env:PATH += ";C:\Users\_**YOUR USERNAME HERE**_\.dotnet\tools" 

and then restarting Rider seems to have fixed it...

Hopefully this can help others too :)

**Comment by seclerp** [comment]
Yes, that's the same issue I've got on my Windows machine after tweaking with .NET SDK not so well

A simpler option for Windows is to open .NET SDK installer and choose "Repair" option, it should resolve all PATH issues

And yes, plugin uses default Java mechanism to run command line commands so it may differ from some custom terminal that you may use

**Comment by joelleibow** [comment]
I'm running into this same issue on MacOS. Within Rider the Entity Framework Core plugin is available within the Tools context but attempting to execute any of the commands leads to:

<img width="379" alt="image" src="https://user-images.githubusercontent.com/157855/164533871-478462c4-521c-4a09-a3ed-a88287afc1f2.png">

Clicking "Fix" leads to:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/157855/164534037-6e6a9636-561c-4a9d-9ae3-eecadd71b5be.png">

`.dotnet/tools` is verified within the zsh path and `dotnet ef --version` has the output below:

```
Entity Framework Core .NET Command-line Tools
6.0.4
```

Any help with getting this functionality would be greatly appreciated! 🖖

**Comment by seclerp** [comment]
@joelleibow could you try to also configure the `.dotnet/tools` path for bash?

**Comment by seclerp** [comment]
@joelleibow are you able to execute `dotnet ef` command from the terminal?

**Comment by joelleibow** [comment]
@seclerp The command above leads to the following error:

```
dotnet ef migrations add SomeMigration
Build started...
Build succeeded.
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 6.0.4 initialized 'TodoContext' using provider 'Microsoft.EntityFrameworkCore.InMemory:6.0.4' with options: StoreName=TodoList
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.InfrastructureExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.DesignTimeServiceCollectionExtensions.<>c__DisplayClass1_0.<AddDbContextDesignTimeServices>b__9(IServiceProvider _)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass2_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.EnsureServices(IServiceProvider services)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to resolve service for type 'Microsoft.EntityFrameworkCore.Migrations.IMigrator'. This is often because no database provider has been configured for this DbContext. A provider can be configured by overriding the 'DbContext.OnConfiguring' method or by using 'AddDbContext' on the application service provider. If 'AddDbContext' is used, then also ensure that your DbContext type accepts a DbContextOptions<TContext> object in its constructor and passes it to the base constructor for DbContext.
```

This is a simple project following the [tutorial here](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api). The associated code leading to the error:

TodoContext.cs
```
using Microsoft.EntityFrameworkCore;
using System.Diagnostics.CodeAnalysis;

namespace TodoApi.Models
{
    public class TodoContext : DbContext
    {
        public TodoContext(DbContextOptions<TodoContext> options)
            : base(options)
        {
        }

        public DbSet<TodoItem> TodoItems { get; set; } = null!;
    }
}
```

And the Program.cs includes:
```
builder.Services.AddDbContext<TodoContext>(opt =>
    opt.UseInMemoryDatabase("TodoList"));
```

**Comment by joelleibow** [comment]
If it's at all helpful, on startup of Rider the IDE now throws.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/157855/164564910-232a07f8-5d18-41d4-843e-8e08c4a15fc1.png">

```
Sync execution of rpc `RiderClientFromEBS.SolutionModel.solutions.[1].riderEfCoreModel.getAvailableStartupProjects` executed too long: 206 ms 

java.lang.Exception
	at com.jetbrains.rd.platform.util.IdeaRdLoggerFactor$getLogger$1.log(IdeaRdLoggerFactor.kt:28)
	at com.jetbrains.rd.util.SwitchLogger.log(Logger.kt:47)
	at com.jetbrains.rd.framework.impl.RdCall.sync(RdTask.kt:228)
	at com.jetbrains.rd.framework.IRdCall$DefaultImpls.sync$default(TaskInterfaces.kt:123)
	at me.seclerp.rider.plugins.efcore.startup.EfCoreStartupActivity.runActivity$lambda-0(EfCoreStartupActivity.kt:21)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:96)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by joelleibow** [comment]
@seclerp Uninstalling the plugin and reinstalling the latest version unfortunately leads to the same errors as mentioned; https://github.com/seclerp/rider-efcore/issues/71#issuecomment-1105645561

**Comment by seclerp** [comment]
@joelleibow I made some work that could potentially fix this issue. I will provide .zip in a few days that you guys will be able to test

**Comment by seclerp** [comment]
Could you guys try this one?

To install it use Gear icon in Plugins page, select Install plugin from disk and provide .zip file:

[riderefcore-1.3.1.1.zip](https://github.com/seclerp/rider-efcore/files/8557108/riderefcore-1.3.1.1.zip)

**Comment by joelleibow** [comment]
Thank you for the zip! After installing it the error no longer occurs at startup. Unfortunately trying to add a migration still leads to the error below along with the error when clicking "Fix".

![image](https://user-images.githubusercontent.com/157855/165369632-f6afc5f0-ab6c-4ccb-9bc6-f9e720a021e4.png)

**Comment by ricardomac** [comment]
**Which worked for me after a few solution attempts.**

I was having the same issue, I was using zsh terminal by default, I decided to switch back to /bin/bash and uninstalled all sdk versions of dotnet and installed it again using bash as the default terminal.
Apparently the plugin works again.

**Comment by seclerp** [comment]
I'm not sure that we will support custom shell environment data in the nearest releases, but an overall issue with EF Core tools detection will be fixed in the next release.

It will be available in **2022.2 EAP** in a couple of days and in **2022.2 stable** once it will be released.

**Comment by seclerp** [comment]
Hey folks - the `222.0.0` version of the plugin is out. The logic of EF Core Tooling detection was refactored, it should work properly from now.

**Comment by seclerp** [comment]
Closing this, if you folks still have issues please open a new issue.
