### ISSUE TITLE
General: RPC timeout on startup after updating Rider and plugin versions

### ISSUE THREAD

**Issue by gushill-ls** [seclerp/rider-efcore#73]
I had just enabled the plugin and restarted Rider. 

Sync execution of rpc `RiderClient.SolutionModel.solutions.[1].riderEfCoreModel.getAvailableStartupProjects` executed too long: 784 ms 

java.lang.Exception
	at com.jetbrains.rd.platform.util.IdeaRdLoggerFactor$getLogger$1.log(IdeaRdLoggerFactor.kt:28)
	at com.jetbrains.rd.util.SwitchLogger.log(Logger.kt:47)
	at com.jetbrains.rd.framework.impl.RdCall.sync(RdTask.kt:228)
	at com.jetbrains.rd.framework.IRdCall$DefaultImpls.sync$default(TaskInterfaces.kt:123)
	at me.seclerp.rider.plugins.efcore.startup.EfCoreStartupActivity.runActivity$lambda-0(EfCoreStartupActivity.kt:21)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:96)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by canine-afficionado** [comment]
Me too

**Comment by seclerp** [comment]
Are you guys able to introduce a reproducible demo project? Can't reproduce it on my side

**Comment by GuentherK** [comment]
Had exactly the same error, but it is impossible for me to reproduce this error because it happend only after updating vom 2021.x to 2022.1 and after installing the suggested plugin (which was your plugin) and another restart of the IDE. Since then the error did not occure anymore.

If that is the case with @gushill-ls and @canine-afficionado we can propably ignore that issue and just leave the issue open for investigation and as an info point for other people?

**Comment by n-shay** [comment]
Same here.

Only occurred once so far since yesterday. I'll post over here if it does again.

**Comment by seclerp** [comment]
I simulated the same circumstances as you folks provided - now I can reproduce it. For now, I'm not sure that this problem is about the plugin itself.

If a problem will occur in other cases - will investigate it further and deeper.

**Comment by joelleibow** [comment]
Maybe relative, https://github.com/seclerp/rider-efcore/issues/71#issuecomment-1105839143

**Comment by seclerp** [comment]
@joelleibow please be more accurate - is your error happens more than 1 time? In which circumstances?

**Comment by joelleibow** [comment]
@seclerp apologies for the slow response

The error occurs on every startup of Rider or attempt to use the context menu options.

**Comment by jloucaosilva** [comment]
It happens to me on every solution I open, latest one was a local repo of [Peasy](https://github.com/peasy/Peasy.NET)

**Comment by seclerp** [comment]
Guys, please, be more specific in your reports. 

Bug is not reproducible on all environments, it will be great if each new related comment will include all (at least basic) env info:
- OS
- Plugin version
- Rider version
- .NET SDK version

In such case shell/terminal configuration is also required.

Also check that you are able to execute `dotnet ef` commands without plugin.

**Comment by n-shay** [comment]
OS: Windows 10 Pro 64-bit
Plugin version:  1.3.1
Rider version: 2022.1 build 221.5080.236
.NET SDK: 6.0

Occurs on every solution opened.

**Comment by seclerp** [comment]
Please take a look at https://github.com/seclerp/rider-efcore/issues/71#issuecomment-1108910434

**Comment by jloucaosilva** [comment]
I'm sorry, I couldn't get to it today.
Third covid shot has me on my knees, going to do it tomorrow

A quinta, 28/04/2022, 22:15, Andrew Rublyov ***@***.***>
escreveu:

**Comment by gushill-ls** [comment]
Very intermittent, but it did just occur again with the newest Rider installed.

OS: macOS Monterey Version 12.3.1
Plugin version: 1.3.1
JetBrains Rider 2022.1.1 Build #RD-221.5591.20, built on April 28, 2022
.NET 6.0.3

**Comment by seclerp** [comment]
@gushill-ls please see https://github.com/seclerp/rider-efcore/issues/73#issuecomment-1112661138

**Comment by jloucaosilva** [comment]
For me, the indicated version solved the startup error, and sorry for taking so long in reporting back.

**Comment by gushill-ls** [comment]
Same here! Thank you, @seclerp

**Comment by seclerp** [comment]
Please also check if with that fix dialogs are also working fine

**Comment by jloucaosilva** [comment]
Ok, I'll test it later

**Comment by GuentherK** [comment]
@seclerp thanks the new version worked perfectly

**Comment by seclerp** [comment]
Thank you guys, the fix will be on the marketplace in the next patch version
