### ISSUE TITLE
cannot select startup project 

### ISSUE THREAD

**Issue by magioloro** [seclerp/rider-efcore#76]
Hi, the Startup Project list is empty for me, and I cannot find any migrations. 
![grafik](https://user-images.githubusercontent.com/56970844/165552307-abad9be1-c67c-42ec-9d04-44149120c338.png)

**Comment by seclerp** [comment]
Hi @magioloro

First of all:

1. Make sure your project and environment follow [plugin's requirements](https://github.com/seclerp/rider-efcore#requirements)
2. Make sure you are using **the latest version** of the plugin and Rider
3. Please **check similar issues**, for example [this one](https://github.com/seclerp/rider-efcore/issues/74) looks familiar

If everything above is fine, provide such information:

1. OS
2. .NET SDK info (installed ones and version used within Rider)
3. Plugin and Rider versions (even if the latest versions are used)

**It is highly recommended** to provide a **minimal solution** that reproduces your issue.

Better issue description - faster issue resolution

**Comment by magioloro** [comment]
Hi,

- my target project is netcoreapp3.1 
- OS: Windows 10 Enterprise 21H1 19043.1682,
- Plugin version 1.3.1, 
- Rider: 2022.1 Build #RD-221.5080.236, built on April 19, 2022
- .Net SDK: 
Version      Status
---------------------------------------------------------------
3.1.418      Auf dem neuesten Stand.
5.0.100      Die Unterstützung von .NET 5.0 läuft in Kürze aus.
5.0.104      Die Unterstützung von .NET 5.0 läuft in Kürze aus.
5.0.213      Die Unterstützung von .NET 5.0 läuft in Kürze aus.
5.0.303      Die Unterstützung von .NET 5.0 läuft in Kürze aus.
5.0.407      Die Unterstützung von .NET 5.0 läuft in Kürze aus.
6.0.104      Auf dem neuesten Stand.
6.0.202      Auf dem neuesten Stand.

**Comment by seclerp** [comment]
Could you introduce a reproducible demo project?

**Comment by magioloro** [comment]
I can try, but it will take time.

**Comment by Maruf61** [comment]
if you don't have "Microsoft.EntityFrameworkCore.Design" package installed on the project, "startup project" list comes empty, maybe button can be added to the UI to auto install that package on selected project?

**Comment by seclerp** [comment]
@Maruf61 it is mentioned in every EF Core tutorial, you are not able to execute CLI commands without such package as well

**Comment by Maruf61** [comment]
I know, i mentioned cuz this issue might be related to that.

**Comment by TropinAlexey** [comment]
> @Maruf61 it is mentioned in every EF Core tutorial, you are not able to execute CLI commands without such package as well

Microsoft.EntityFrameworkCore.Tools are responsible for that

**Comment by seclerp** [comment]
> > @Maruf61 it is mentioned in every EF Core tutorial, you are not able to execute CLI commands without such package as well
> 
> Microsoft.EntityFrameworkCore.Tools are responsible for that

`.Tools` or `.Design`, both of them could be used

**Comment by seclerp** [comment]
@magioloro do you have any further information or reproducible project?

**Comment by seclerp** [comment]
Please explain what you mean by implicit reference

cc @kolosovpetro

**Comment by magioloro** [comment]
![grafik](https://user-images.githubusercontent.com/56970844/167391761-9b238cfb-d15f-4ae5-add7-e8f0df451442.png)

**Comment by seclerp** [comment]
Show your .csproj for startup project or create a reproducible project that you could share with us.

**Comment by magioloro** [comment]
`<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <IncludeOpenAPIAnalyzers>true</IncludeOpenAPIAnalyzers>
    <DockerTargetOS>Linux</DockerTargetOS>
    <AssemblyName>Api</AssemblyName>
    <RootNamespace>Api</RootNamespace>
    <Nullable>warnings</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <DocumentationFile>.\Sicat.Portal.SiDops.Api.xml</DocumentationFile>
    <LangVersion>8</LangVersion>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Connected Services\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="IdentityServer4.AccessTokenValidation" Version="3.0.1"/>
      <PackageReference Include="xxx" Version="3.1.325"/>
      <PackageReference Include="xxx" Version="3.1.325"/>
      <PackageReference Include="xxx" Version="3.1.325"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Client\Ecommerce.Client.csproj" />
    <ProjectReference Include="..\DataModels\DataModels.csproj" />
    <ProjectReference Include="..\Domain\s.Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\.Infrastructure.csproj" />
  </ItemGroup>

 

    <ItemGroup>
        <WCFMetadata Include="Connected Services" />
    </ItemGroup>

</Project>
`

**Comment by seclerp** [comment]
It is not so useful information, we are waiting for solution that could be reproduced.

**Comment by magioloro** [comment]
I can't do it at the moment, but I have a new error:

com.jetbrains.rdclient.util.BackendException: The data context is outdated. Objektname: "DataContext".

--- EXCEPTION #1/2 [ObjectDisposedException]
Message = “The data context is outdated.”
ExceptionPath = Root.InnerException
ClassName = System.ObjectDisposedException
HResult = COR_E_OBJECTDISPOSED=80131622
ObjectName = DataContext

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “
  The data context is outdated.
  Objektname: "DataContext".
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
InnerException = “Exception #1 at Root.InnerException”
HResult = COR_E_APPLICATION=80131600
StackTraceString = “
  bei JetBrains.Util.LoggerBase.Log(LoggingLevel level, String message, Exception ex)
     bei JetBrains.Application.DataContext.DataContext.JetBrains.Application.DataContext.IDataContext.GetData[T](DataConstant`1 dataConstant)
     bei JetBrains.ReSharper.Feature.Services.QuickDoc.QuickDocCandidatesProvider.CanNavigate(IDataContext context)
     bei System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
     bei JetBrains.Rider.Backend.Features.QuickDoc.QuickDocHost.<>c__DisplayClass13_2.<.ctor>b__3()
     bei JetBrains.Application.Threading.IShellLocksExAsync.<>c__DisplayClass6_0.<StartBackgroundInterruptableRead>b__0()
     bei JetBrains.Application.Threading.IShellLocksExAsync.<>c__DisplayClass7_0`1.<StartBackgroundInterruptableRead>b__0()
     bei JetBrains.Application.Threading.IShellLocksExAsync.<>c__DisplayClass9_0`1.<<StartBackgroundRead>b__0>d.MoveNext()
     bei System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
     bei JetBrains.Application.Threading.IShellLocksExAsync.<>c__DisplayClass9_0`1.<StartBackgroundRead>b__0()
     bei System.Threading.Tasks.Task`1.InnerInvoke()
     bei System.Threading.Tasks.Task.Execute()
     bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     bei System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     bei JetBrains.Application.Threading.Tasks.Scheduler.JetScheduler.ExecuteTask(Task task)
     bei JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.EnqueueNextTask()
     bei JetBrains.Application.Threading.Tasks.Scheduler.JetSchedulerThread.ThreadPoolProc()
     bei JetBrains.Util.Reflection.CallStackAnnotation.CatchAnnotatedInvocation[TClassOfNewFrame](String methodNameOfNewFrame, Action actionToAnnotate)
     bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
     bei System.Threading.ThreadHelper.ThreadStart()
”

	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:47)
	at com.jetbrains.rdclient.protocol.components.RdClientProtocolComponent$2.invoke(RdClientProtocolComponent.kt:22)
	at com.jetbrains.rd.util.reactive.Signal.fire(Signal.kt:32)
	at com.jetbrains.rd.framework.impl.RdSignal.onWireReceived(RdSignal.kt:42)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rdclient.protocol.RdDispatcher.pumpProtocolQueue(RdDispatcher.kt:72)
	at com.jetbrains.rider.services.RiderGlobalProgressHostKt.runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:108)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.V(RiderGlobalProgressHost.kt:90)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.access$runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:62)
	at com.jetbrains.rider.services.RiderGlobalProgressHost.runProgress(RiderGlobalProgressHost.kt:59)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runUnderProgress(Extensions.kt:121)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.migrationsProjectChanged(EfCoreDialogWrapper.kt:282)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.access$migrationsProjectChanged(EfCoreDialogWrapper.kt:23)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$1.invoke(EfCoreDialogWrapper.kt:85)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$1.invoke(EfCoreDialogWrapper.kt:85)
	at me.seclerp.rider.plugins.efcore.Event.invoke(Event.kt:16)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.migrationsProjectSetter(EfCoreDialogWrapper.kt:246)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.access$migrationsProjectSetter(EfCoreDialogWrapper.kt:23)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMigrationsProjectRow$1$2.invoke(EfCoreDialogWrapper.kt:191)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMigrationsProjectRow$1$2.invoke(EfCoreDialogWrapper.kt:191)
	at me.seclerp.rider.plugins.efcore.ui.DslExtensionsKt$iconComboBox$1.invoke$lambda-0(DslExtensions.kt:43)
	at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1227)
	at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1288)
	at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1335)
	at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:123)
	at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:579)
	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:907)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6654)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:551)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2793)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:820)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:743)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:702)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:439)
	at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1668)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1626)
	at com.intellij.openapi.ui.DialogWrapper.showAndGet(DialogWrapper.java:1640)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction.ready(AddMigrationAction.kt:17)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreAction$actionPerformed$1.run$lambda-0(EfCoreAction.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

**Comment by biel-correa** [comment]
Something similar is happening with me but I can't select anything.
![image](https://user-images.githubusercontent.com/56176344/172912439-66da4d89-5734-40cb-8003-fd6660aca93f.png)
all of these doesn't have any options

**Comment by seclerp** [comment]
@biel-correa please share your target framework information for expected projects

**Comment by biel-correa** [comment]
Thanks @seclerp the problem was the version, do you know any other extension for this that may suport older versions?

**Comment by seclerp** [comment]
I don't know for sure but you could try https://github.com/minasploit/migration-facilitator

**Comment by seclerp** [comment]
@magioloro are you able to provide reproducible project?

**Comment by magioloro** [comment]
No sorry, it's too laborious for me at the moment.
