### ISSUE TITLE
Null Ref adding new migration

### ISSUE THREAD

**Issue by ryburn52** [seclerp/rider-efcore#87]
Lately i have been unable to add any migrations using this plugin. I get the following exception

```
com.jetbrains.rd.util.reactive.RdFault: Object reference not set to an instance of an object., reason: System.NullReferenceException: Object reference not set to an instance of an object.
   at Rider.Plugins.EfCore.Extensions.PsiExtensions.ToMigrationInfo(IClass class) in /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/Extensions/PsiExtensions.cs:line 22
   at Rider.Plugins.EfCore.EfCoreSolutionComponent.<>c.<GetAvailableMigrations>b__5_2(IClass migrationClass) in /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/EFCoreSolutionComponent.cs:line 110
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Rider.Plugins.EfCore.EfCoreSolutionComponent.GetAvailableMigrations(Lifetime lifetime, MigrationsIdentity identity) in /home/runner/work/rider-efcore/rider-efcore/src/dotnet/Rider.Plugins.EfCore/EFCoreSolutionComponent.cs:line 106
   at JetBrains.Rd.Tasks.RdCall`2.OnWireReceived(UnsafeReader reader)
	at com.jetbrains.rd.framework.RdTaskResult$Companion.read(TaskInterfaces.kt:30)
	at com.jetbrains.rd.framework.impl.CallSiteWiredRdTask.onWireReceived(RdTask.kt:98)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:57)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rd.framework.impl.ProtocolContexts.readMessageContextAndInvoke(ProtocolContexts.kt:151)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:56)
	at com.jetbrains.rd.framework.MessageBroker$invoke$2.invoke(MessageBroker.kt:12)
	at com.jetbrains.rdclient.protocol.RdDispatcher.flushAll(RdDispatcher.kt:97)
	at com.jetbrains.rdclient.protocol.RdDispatcher.access$flushAll(RdDispatcher.kt:18)
	at com.jetbrains.rdclient.protocol.RdDispatcher$flushAllRunnable$1.run(RdDispatcher.kt:23)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:119)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:943)
	at com.intellij.openapi.progress.util.ProgressWindow.lambda$startBlocking$4(ProgressWindow.java:205)
	at com.intellij.openapi.application.impl.ApplicationImpl.runUnlockingIntendedWrite(ApplicationImpl.java:899)
	at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:201)
	at com.jetbrains.rider.services.RiderGlobalProgressHostKt.runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:155)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.i(RiderGlobalProgressHost.kt:90)
	at com.jetbrains.rider.services.RiderGlobalProgressHost$Companion.access$runSynchronouslyUnderProgress(RiderGlobalProgressHost.kt:62)
	at com.jetbrains.rider.services.RiderGlobalProgressHost.runProgress(RiderGlobalProgressHost.kt:59)
	at com.jetbrains.rider.util.idea.ExtensionsKt.runUnderProgress(Extensions.kt:121)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.refreshAvailableMigrations(AddMigrationDialogWrapper.kt:125)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.onMigrationsProjectChanged(AddMigrationDialogWrapper.kt:105)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.access$onMigrationsProjectChanged(AddMigrationDialogWrapper.kt:20)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper$1.invoke(AddMigrationDialogWrapper.kt:45)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper$1.invoke(AddMigrationDialogWrapper.kt:45)
	at me.seclerp.rider.plugins.efcore.Event.invoke(Event.kt:16)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.migrationsProjectSetter(EfCoreDialogWrapper.kt:246)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.refreshProjectsPair(EfCoreDialogWrapper.kt:129)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.initProjectLevelPreferredProjects(EfCoreDialogWrapper.kt:125)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.initPreferredProjects(EfCoreDialogWrapper.kt:107)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.access$initPreferredProjects(EfCoreDialogWrapper.kt:23)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1$1.invoke(EfCoreDialogWrapper.kt:171)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1$1.invoke(EfCoreDialogWrapper.kt:168)
	at com.intellij.ui.dsl.builder.impl.RowImpl.panel(RowImpl.kt:188)
	at com.intellij.ui.dsl.builder.impl.RowImpl.panel(RowImpl.kt:47)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$panel$1.invoke(PanelImpl.kt:155)
	at com.intellij.ui.dsl.builder.impl.PanelImpl$panel$1.invoke(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:66)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.row(PanelImpl.kt:24)
	at com.intellij.ui.dsl.builder.Panel$DefaultImpls.row$default(Panel.kt:57)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.panel(PanelImpl.kt:154)
	at com.intellij.ui.dsl.builder.impl.PanelImpl.panel(PanelImpl.kt:24)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1.invoke(EfCoreDialogWrapper.kt:168)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper$createMainUI$1.invoke(EfCoreDialogWrapper.kt:167)
	at com.intellij.ui.dsl.builder.BuilderKt.panel(builder.kt:19)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.createMainUI(EfCoreDialogWrapper.kt:167)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreDialogWrapper.createCenterPanel(EfCoreDialogWrapper.kt:164)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1308)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationDialogWrapper.<init>(AddMigrationDialogWrapper.kt:48)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction$ready$dialog$1.invoke(AddMigrationAction.kt:14)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction$ready$dialog$1.invoke(AddMigrationAction.kt:13)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreAction.buildDialogInstance(EfCoreAction.kt:69)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction.ready(AddMigrationAction.kt:13)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreAction$actionPerformed$1.run$lambda-0(EfCoreAction.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```

**Comment by seclerp** [comment]
Hi @ryburn52, please re-create the issue using the **Bug report** template, you should provide all necessary information to help you.

**Comment by ryburn52** [comment]
Sorry not sure how i missed that

**Comment by ryburn52** [comment]
https://github.com/seclerp/rider-efcore/issues/88
