### ISSUE TITLE
Can not make migration

### ISSUE THREAD

**Issue by MichaelAggerholm** [seclerp/rider-efcore#99]
I am trying to make a simple migration from following the official Microsoft "RazorPagesMovie" guide, i have:
1. Created Models folder with Movie class.
2. Created scaffolded item in Pages/Movies folder.
3. Installed plugin Entity Framework Core UI
4. Tools/Entity Framework Core/Make Migration
5. Choosing my project, Startup project and class.
6. Skip project build process since i have no build process for this project.
7. "OK"
But i get the error below:
"IDE Internal Errors"
```
java.lang.NullPointerException
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreAction.getCommonOptions(EfCoreAction.kt:33)
	at me.seclerp.rider.plugins.efcore.features.migrations.add.AddMigrationAction.ready(AddMigrationAction.kt:19)
	at me.seclerp.rider.plugins.efcore.features.shared.EfCoreAction$actionPerformed$1.run$lambda-0(EfCoreAction.kt:48)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)

```
- OS: Linux Ubuntu 22.04
- .NET SDK info (installed ones and version used within Rider): 6.0.302
- Plugin version: 1.4.0 by Andrew Rublyov
- Rider version: Build #RD-221.5787.36, built on June 1, 2022 With .NET 6.0.3

Can someon describe to me how to fix this? been googling all night without luck. 
I have added image of error below:
![jetbrains_error](https://user-images.githubusercontent.com/61044186/180873997-64ed0fd3-84ed-4dfd-85b2-bf48ca68f378.png)

**Comment by seclerp** [comment]
Hi @MichaelAggerholm, please add all required information from Bug report template.

**Comment by MichaelAggerholm** [comment]
> Hi @MichaelAggerholm, please add all required information from Bug report template.

Thank you @seclerp and sorry for the missing information

**Comment by seclerp** [comment]
What do you mean by not having build process for your project? And what about your available build configurations?

**Comment by MichaelAggerholm** [comment]
@seclerp 
![image](https://user-images.githubusercontent.com/61044186/180875300-56e2f24f-9c48-422f-949e-b58721ec504a.png)
"Solution doesnt have any build configurations"

I created the project with terminal command: dotnet new webapp -o RazorPagesMovie
And from what i can see, it should not break the add of migration by using --no-build ?

**Comment by MichaelAggerholm** [comment]
@seclerp 
I have here another screenshot of my trying to add the configuration, but on clicking the <No Configuration> dropdown, i get the text: "Nothing here"

![image](https://user-images.githubusercontent.com/61044186/180876084-a21175ea-e862-4015-90b8-b35bc1d866c7.png)

**Comment by seclerp** [comment]
@MichaelAggerholm sorry for the late response. 

We are not supporting single project cases (I mean, when you open `csproj` files directly in Rider, not `sln` ones).

So I suggest you to create a solution that will contain build configurations (Debug/Release) alongside with your project and then open it in Rider.

And you should not check "No Build" checkbox, it's for special cases only.

**Comment by seclerp** [comment]
@MichaelAggerholm sorry for the late response. 

We are not supporting single project cases (I mean, when you open `csproj` files directly in Rider, not `sln` ones).

So I suggest you to create a solution that will contain build configurations (Debug/Release) alongside with your project and then open it in Rider.

And you should not check "No Build" checkbox, it's for special cases only.
